### PR TITLE
Add support to log == 0.4.10.

### PR DESCRIPTION
**Pull request by singulared**
This commit update signature of private log api, changed in log crate version 0.4.10.

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
I'll need someone reminding me to test, land and release.

**Comment by singulared** [comment]
Ok, np. Thanks a lot.

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
https://crates.io/crates/log

 0.4.10 Dec 15, 2019 yanked
0.4.9 Dec 15, 2019 yanked 

Was I too slow? :D

**Comment by dpc** [comment]
Oh. It seems there has been some other problems and they had been yanked. The code is ready in master - I additionally bumped the dependency on `log` to be `0.4.10`. But I'm not sure if I should publish it now, since `log 0.4.10` is yanked. Could it force `cargo` to use yanked version? I'm not sure.

@KodrAus @sfackler - I just sent you invites with more permissions so you should be able to land and publish changes to this crate. Please don't feel like I try to drop the responsibility of maintaining it on you (though you're welcome to if you want :laughing: ). It is purely optional: in case you have to break some API that this crate depends on etc. you might want to use this permissions to swiftly fix any users of this crate as well.

**Comment by singulared** [comment]
You can't use a yanked version. Btw now I didn't see this API changes in log master branch.
https://github.com/rust-lang/log/blob/master/src/lib.rs#L1368
Maybe it will be better revert this PR?

**Comment by dpc** [comment]
@singulared This api is private, always been documented as such, and it is `slog-stdlog` "fault" to use it (there was no other way). I don't think `log` developers should be hindered by `slog-stdlog` using a private detail, and I personally root for `log` to add structured logging support.

The only thing we can do is to help users easily migrate though this breakage.

**Pull request merged**
