### PR TITLE
Log 0.4 support

### PR DESCRIPTION
**Pull request by jacekchmiel**

### CODE REVIEW

**Comment by breezewish** [comment]
Are there plans to merge?

**Comment by dpc** [comment]
Anyone willing to take ownership and maintain this crate?

**Comment by siddontang** [comment]
Hi @dpc 

Now we are heavily using slog and stdlog in [TiKV](https://github.com/tikv/tikv), so if you don't mind, we can take the ownership of this crate. 

you can add @breeswish and @hoverbear  to the owner.

**Comment by siddontang** [comment]
now using stdlog with slog will output "Unknow" for the file, and we want to fix it.  :-)

**Comment by dpc** [comment]
@siddontang Thank you. I've added you as an Admin. Feel free to organize it according to your own needs.

**Comment by dpc** [comment]
@siddontang  On crates.io:

```
       Owner user siddontang has been invited to be an owner of crate slog-stdlog
```

**Comment by siddontang** [comment]
Thanks @dpc 

We will improve stdlog ASAP.

**Comment by pravic** [comment]
Hi, any news on this?

**Comment by belltoy** [comment]
@siddontang 合并一下？

**Comment by mbilker** [comment]
Well, this is a bit of a hard one. If the main `slog` crate migrates to using borrowed values for `file` and `module` in `RecordLocation`, then it would be possible to use the information from `log::Record`. Otherwise, the only value that can be used is some placeholder value like `<unknown>`.

Also, it is possible to use `format_args!` with `LazyLogString`, but you cannot store the `log::Record` into a variable. The record must be immediately passed into `log::logger().log`.
```rust
let lazy = LazyLogString::new(info, logger_values);
log::logger().log(&log::Record::builder()
    .args(format_args!("{}", lazy))
    .level(level)
    .target(target)
    .file(Some(info.file()))
    .line(Some(info.line()))
    .module_path(Some(info.module()))
    .build());
```

**Comment by Hoverbear** [comment]
@mbilker Can you open an issue about this there?

**Comment by mbilker** [comment]
@Hoverbear Comment on the main `slog` repository about using borrowed values that are not `'static`?

It would probably be easier to use `Cow<'static, str>`.

**Comment by spease** [comment]
Is this crate still being maintained? The lack of log 0.4 is a consistent papercut for using `cargo upgrade` with a team project. I was coming on here to see if it was a simple fix.

**Comment by dpc** [comment]
@spease I'm alive and well, but can't actively dedicate the time to solve it. Someone actually bothered by this will have to step in and address the problem.

**Comment by dpc** [comment]
I think https://github.com/slog-rs/stdlog/pull/9 made this obsolete.

**Pull request closed without merging**
